const COMMUNITY_COLLECTION_NAME = "community";
const COMMUNITY_POST_SEARCHABLE_FIELD = ["text"];

const COMMUNITY_POST_TYPES = {
  TEXT: "TEXT",
  IMAGE: "IMAGE",
  POST_SHARE: "POST_SHARE",
  POLL: "POLL",
  QUIZ: "QUIZ",
};

const COMMUNITY_TEXT_MIN_LENGTH = 2;
const COMMUNITY_TEXT_MAX_LENGTH = 200;

const COMMUNITY_OPTION_MIN_LENGTH = 1;
const COMMUNITY_OPTION_MAX_LENGTH = 80;

const COMMUNITY_MIN_OPTION_IN_EACH_POST = 2;

export const CommunityConstant = {
  COMMUNITY_COLLECTION_NAME,
  COMMUNITY_POST_SEARCHABLE_FIELD,
  COMMUNITY_POST_TYPES,
  COMMUNITY_TEXT_MIN_LENGTH,
  COMMUNITY_TEXT_MAX_LENGTH,
  COMMUNITY_OPTION_MIN_LENGTH,
  COMMUNITY_OPTION_MAX_LENGTH,
  COMMUNITY_MIN_OPTION_IN_EACH_POST,
};
