const COMMUNITY_COLLECTION_NAME = "community";

const COMMUNITY_POST_TYPES = {
  TEXT: "TEXT",
  IMAGE: "IMAGE",
  POST_SHARE: "POST_SHARE",
  POLL: "POLL",
  QUIZ: "QUIZ",
};

const COMMUNITY_TEXT_MIN_LENGTH = 2;
const COMMUNITY_TEXT_MAX_LENGTH = 200;

export const CommunityConstant = {
  COMMUNITY_COLLECTION_NAME,
  COMMUNITY_POST_TYPES,
  COMMUNITY_TEXT_MIN_LENGTH,
  COMMUNITY_TEXT_MAX_LENGTH,
};
