const SHARE_THOUGHT_ROOT_FOLDER_NAME = "shareThoughtTemp";
const SHARE_THOUGHT_USER_FOLDER_NAME = "user";
const SHARE_THOUGHT_POST_FOLDER_NAME = "post";
const SHARE_THOUGHT_COMMENT_FOLDER_NAME = "comment";
const SHARE_THOUGHT_CHANNEL_FOLDER_NAME = "channel";
const SHARE_THOUGHT_COMMUNITY_POST_FOLDER_NAME = "community_post";

const SHARE_THOUGHT_POST_BANNER_FOLDER_NAME = `${SHARE_THOUGHT_POST_FOLDER_NAME}/post_banner`;
const SHARE_THOUGHT_POST_CONTENT_FOLDER_NAME = `${SHARE_THOUGHT_POST_FOLDER_NAME}/post_content`;

const SHARE_THOUGHT_CHANNEL_AVATAR_FOLDER_NAME = `${SHARE_THOUGHT_CHANNEL_FOLDER_NAME}/avatar`;
const SHARE_THOUGHT_CHANNEL_COVER_FOLDER_NAME = `${SHARE_THOUGHT_CHANNEL_FOLDER_NAME}/cover`;

const SHARE_THOUGHT_COMMUNITY_POST_IMAGE_POST_FOLDER_NAME = `${SHARE_THOUGHT_COMMUNITY_POST_FOLDER_NAME}/image_post`;
const SHARE_THOUGHT_COMMUNITY_POST_POLL_POST_FOLDER_NAME = `${SHARE_THOUGHT_COMMUNITY_POST_FOLDER_NAME}/poll_post`;

export const CloudinaryConstant = {
  SHARE_THOUGHT_ROOT_FOLDER_NAME,
  SHARE_THOUGHT_USER_FOLDER_NAME,
  SHARE_THOUGHT_POST_FOLDER_NAME,
  SHARE_THOUGHT_POST_BANNER_FOLDER_NAME,
  SHARE_THOUGHT_POST_CONTENT_FOLDER_NAME,
  SHARE_THOUGHT_CHANNEL_FOLDER_NAME,
  SHARE_THOUGHT_CHANNEL_COVER_FOLDER_NAME,
  SHARE_THOUGHT_CHANNEL_AVATAR_FOLDER_NAME,
  SHARE_THOUGHT_COMMENT_FOLDER_NAME,
  SHARE_THOUGHT_COMMUNITY_POST_FOLDER_NAME,
  SHARE_THOUGHT_COMMUNITY_POST_IMAGE_POST_FOLDER_NAME,
  SHARE_THOUGHT_COMMUNITY_POST_POLL_POST_FOLDER_NAME,
};
