const SHARE_THOUGHT_ROOT_FOLDER_NAME = "shareThought";
const SHARE_THOUGHT_USER_FOLDER_NAME = "user";
const SHARE_THOUGHT_POST_FOLDER_NAME = "post";
const SHARE_THOUGHT_CHANNEL_FOLDER_NAME = "channel";
const SHARE_THOUGHT_CHANNEL_AVATAR_NAME = `${SHARE_THOUGHT_CHANNEL_FOLDER_NAME}/avatar`;
const SHARE_THOUGHT_CHANNEL_COVER_NAME = `${SHARE_THOUGHT_CHANNEL_FOLDER_NAME}/cover`;

export const CloudinaryConstant = {
  SHARE_THOUGHT_ROOT_FOLDER_NAME,
  SHARE_THOUGHT_USER_FOLDER_NAME,
  SHARE_THOUGHT_POST_FOLDER_NAME,
  SHARE_THOUGHT_CHANNEL_FOLDER_NAME,
  SHARE_THOUGHT_CHANNEL_COVER_NAME,
  SHARE_THOUGHT_CHANNEL_AVATAR_NAME,
};
