const CATEGORY_COLLECTION_NAME = "category";
const CATEGORY_DESCRIPTION_MIN_LENGTH = 10;
const CATEGORY_DESCRIPTION_MAX_LENGTH = 250;
const CATEGORY_NAME_MIN_LENGTH = 1;
const CATEGORY_NAME_MAX_LENGTH = 50;

const CATEGORY_ACCESS_TYPE = {
  PUBLIC: "PUBLIC",
  UNLISTED: "UNLISTED",
  PRIVATE: "PRIVATE",
};

export const CategoryConstant = {
  CATEGORY_COLLECTION_NAME,
  CATEGORY_DESCRIPTION_MIN_LENGTH,
  CATEGORY_DESCRIPTION_MAX_LENGTH,
  CATEGORY_NAME_MAX_LENGTH,
  CATEGORY_NAME_MIN_LENGTH,
  CATEGORY_ACCESS_TYPE,
};
