const COMMUNITY_POST_COLLECTION_NAME = "community_post";
const COMMUNITY_POST_SEARCHABLE_FIELD = ["text"];

const COMMUNITY_POST_TYPES = {
  TEXT: "TEXT",
  IMAGE: "IMAGE",
  POST_SHARE: "POST_SHARE",
  POLL: "POLL",
  POLL_WITH_IMAGE: "POLL_WITH_IMAGE",
  QUIZ: "QUIZ",
};

const COMMUNITY_POST_TEXT_MIN_LENGTH = 2;
const COMMUNITY_POST_TEXT_MAX_LENGTH = 200;

const COMMUNITY_POST_OPTION_MIN_LENGTH = 1;
const COMMUNITY_POST_OPTION_MAX_LENGTH = 80;

const COMMUNITY_POST_MIN_OPTION_IN_EACH_POST = 2;

const COMMUNITY_POST_IMAGE_DIMENSION = {
  WIDTH: 500,
  HEIGHT: 500,
};

const COMMUNITY_POST_POLL_IMAGE_DIMENSION = {
  WIDTH: 50,
  HEIGHT: 50,
};

export const CommunityPostConstant = {
  COMMUNITY_POST_COLLECTION_NAME,
  COMMUNITY_POST_SEARCHABLE_FIELD,
  COMMUNITY_POST_TYPES,
  COMMUNITY_POST_TEXT_MIN_LENGTH,
  COMMUNITY_POST_TEXT_MAX_LENGTH,
  COMMUNITY_POST_OPTION_MIN_LENGTH,
  COMMUNITY_POST_OPTION_MAX_LENGTH,
  COMMUNITY_POST_MIN_OPTION_IN_EACH_POST,
  COMMUNITY_POST_IMAGE_DIMENSION,
  COMMUNITY_POST_POLL_IMAGE_DIMENSION,
};
