const REPORT_COLLECTION_NAME = "Report_collection";

const REPORT_TYPES = {
  SPAM: "SPAM",
  HARASSMENT_OR_BULLYING: "HARASSMENT_OR_BULLYING",
  HATE_SPEECH: "HATE SPEECH",
  MISINFORMATION: "MISINFORMATION",
  INAPPROPRIATE_CONTENT: "INAPPROPRIATE_CONTENT",
  ADULT_CONTENT: "ADULT_CONTENT",
  PLAGIARISM: "PLAGIARISM",
  ILLEGAL_ACTIVITY: "ILLEGAL_ACTIVITY",
  SELF_HARM_OR_SUICIDE: "SELF_HARM_OR_SUICIDE",
  VIOLENCE_OR_THREATS: "VIOLENCE_OR_THREATS",
  IMPERSONATION: "IMPERSONATION",
  OFF_TOPIC: "OFF_TOPIC",
  COPYRIGHT_VIOLATION: "COPYRIGHT_VIOLATION",
  PRIVACY_VIOLATION: "PRIVACY_VIOLATION",
  OTHER: "OTHER",
};

const REPORT_CONTEXT_TYPES = {
  CHANNEL: "CHANNEL",
  BLOG_POST: "BLOG_POST",
  COMMUNITY_POST: "COMMUNITY_POST",
  POST: "POST",
  COMMENT: "COMMENT",
};

const REPORT_RESPONSE_TYPES = {
  ACCEPTED: "ACCEPTED",
  REJECTED: "REJECTED",
  PENDING: "PENDING",
};

export const ReportConstant = {
  REPORT_COLLECTION_NAME,
  REPORT_TYPES,
  REPORT_CONTEXT_TYPES,
  REPORT_RESPONSE_TYPES,
};
