const SEARCH_HISTORY_COLLECTION_NAME = "search_history";
const SEARCH_HISTORY_SEARCHABLE_FIELD = ["searchTerm"];

export const SearchHistoryConstant = {
  SEARCH_HISTORY_COLLECTION_NAME,
  SEARCH_HISTORY_SEARCHABLE_FIELD,
};
